version: '3'
services:
  redis-server:
    container_name: redis
    image: 'redis:7.0.4'
    ports:
      - "6379:6379"
  java-service:
    build: .
    links:
      - redis-server
    ports:
      - "8080:8080"
