openapi: 3.0.0
info:
  title: credential-api
  description: API til vedligehold af credential til IHE XDS
  version: "1.0.0"
  contact:
    email: development@kvalitetitsit.dk
tags:
  - name: credential-api
    description: API til vedligehold af credential til IHE XDS

servers:
  - url: '{protocol}://{environment}:{port}'
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      environment:
        enum:
          - localhost # Docker-compose setup
        default: localhost # Development
      port:
        enum:
          - 8080
        default: 8080
paths:
  /v1/credentialinfo:
    get:
      tags:
        - CredentialInfo
      summary: Call the thugs service
      description: Post your name and get some hugs or meet some thugs.
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/credentialInfoResponse'

components:
  responses:
    '400':
      description: "Bad Request. This could be because: * One of the required parameters/properties are missing or is empty <br> * Length of input is exceeding maximum length <br> (See a possible detailed error message in the in the response.)"
    '401':
      description: "Unauthorized. This could be because: <br> * The calling system has not been properly authenticated."
    '403':
      description: "Forbidden. This could be because: <br> * The requested information does not belong the organisation of the user <br> * The calling user does not have the required roles"
  schemas:
    credentialInfoResponse:
      type: object
      required:
        - id
      properties:
        id:
          description: Credential Id
          type: string
          nullable: false
          example: "458abc"
