openapi: 3.0.0
info:
  title: credential-api
  description: API til vedligehold af credential til IHE XDS
  version: "1.0.0"
  contact:
    email: development@kvalitetitsit.dk
tags:
  - name: credential-api
    description: API til vedligehold af credential til IHE XDS

servers:
  - url: '{protocol}://{environment}:{port}'
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      environment:
        enum:
          - localhost # Docker-compose setup
        default: localhost # Development
      port:
        enum:
          - 8080
        default: 8080
paths:

  /v1/credentialinfo:
    get:
      tags:
        - Credentials
      summary: Get all the shared credential infos as well as the ones owned by the owner
      description: Find all the credential infos
      parameters:
        - in: query
          name: owner
          schema:
            type: string
          required: false
          description: The id of the owner of the credential infos - if not supplied only shared credential infos are returned

      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/credentialInfoResponse'
        '404':
          description: Credential info not found
    put:
      tags:
        - Credentials
        - Upload
      summary: Upload a new credential for a specific owner.
      description: Upload new credential.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createCredentialResponse'
      responses:
        '201':
          description: Certificate uploaded



components:
  responses:
    '400':
      description: "Bad Request. This could be because: * One of the required parameters/properties are missing or is empty <br> * Length of input is exceeding maximum length <br> (See a possible detailed error message in the in the response.)"
    '401':
      description: "Unauthorized. This could be because: <br> * The calling system has not been properly authenticated."
    '403':
      description: "Forbidden. This could be because: <br> * The requested information does not belong the organisation of the user <br> * The calling user does not have the required roles"
  schemas:
    credentialInfoResponse:
      type: object
      required:
        - id
      properties:
        id:
          description: Credential Id
          type: string
          nullable: false
          example: "458abc"

    createCredentialResponse:
      type: object
      required:
        - owner
        - id
        - cvr
        - organisation
        - publicCertStr
        - privateKeyStr
      properties:
        owner:
          description: Owner of the credential
          type: string
          nullable: false
          example: "John Doe"
        id:
          description: Credential Id
          type: string
          nullable: false
          example: "458abc"
        cvr:
          description: CVR for the Credential
          type: string
          nullable: false
          example: "1234AAbb"
        organisation:
          description: Organisation for Credential
          type: string
          nullable: false
          example: "Best Buy org"
        publicCertStr:
          description: Certificate for Credential
          type: string
          nullable: false
          example: "-----BEGIN CERTIFICATE----- ..... -----END CERTIFICATE-----   DER format"
        privateKeyStr:
          description: Private key for uploader
          type: string
          nullable: false
          example: "-----BEGIN PRIVATE KEY----- ..... -----END PRIVATE KEY-----  RSA format"