openapi: 3.0.0
info:
  title: credential-api
  description: API til vedligehold af credential til IHE XDS
  version: "1.0.0"
  contact:
    email: development@kvalitetitsit.dk
tags:
  - name: credential-api
    description: API til vedligehold af credential til IHE XDS

servers:
  - url: '{protocol}://{environment}:{port}'
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      environment:
        enum:
          - localhost # Docker-compose setup
        default: localhost # Development
      port:
        enum:
          - 8080
        default: 8080
paths:

  /v1/credentialinfo:
    get:
      tags:
        - Credentials
      summary: Get all the shared credential infos as well as the ones owned by the owner
      description: Find all the credential infos
      parameters:
        - in: query
          name: owner
          schema:
            type: string
          required: false
          description: The id of the owner of the credential infos - if not supplied only shared credential infos are returned

      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/credentialInfoResponse'
        '404':
          description: Credential info not found
    put:
      tags:
        - Credentials
        - Upload
      summary: Upload a new credential for a specific owner.
      description: Upload new credential.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createCredentialRequest'
      responses:
        '201':
          description: Certificate uploaded
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/basic_error'
        '404':
          description: Bad resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/basic_error'





components:
  responses:
    '400':
      description: "Bad Request. This could be because: * One of the required parameters/properties are missing or is empty <br> * Length of input is exceeding maximum length <br> (See a possible detailed error message in the in the response.)"
    '401':
      description: "Unauthorized. This could be because: <br> * The calling system has not been properly authenticated."
    '403':
      description: "Forbidden. This could be because: <br> * The requested information does not belong the organisation of the user <br> * The calling user does not have the required roles"
  schemas:
    credentialInfoResponse:
      type: object
      required:
        - id
      properties:
        id:
          description: Credential Id
          type: string
          nullable: false
          example: "458abc"
        displayName:
          description: Display name for certificate
          type: string
          nullable: false
          example: "My certificte"

    createCredentialRequest:
      type: object
      required:
        - displayName
        - publicCertStr
        - privateKeyStr
      properties:
        owner:
          description: Owner of the credential
          type: string
          nullable: false
          example: "John Doe"
        displayName:
          description: Name of the certificate on the UI
          type: string
          nullable: false
          example: "My certificate"
        publicCertStr:
          description: Certificate for Credential
          type: string
          nullable: false
          example: "-----BEGIN CERTIFICATE----- ..... -----END CERTIFICATE-----   DER format"
        privateKeyStr:
          description: Private key for uploader
          type: string
          nullable: false
          example: "-----BEGIN PRIVATE KEY----- ..... -----END PRIVATE KEY-----  RSA format"

    basic_error:
      type: object
      required:
        - error_code
        - error
        - path
        - status
        - status_text
        - timestamp
      properties:
        error_code:
          description: Error code
          type: integer
        error:
          description: Error message.
          type: string
        path:
          description: Path
          type: string
        status:
          description: HTTP status code
          type: integer
        status_text:
          description: HTTP status text
          type: string
        timestamp:
          description: Time of error
          type: string
          format: date-time