openapi: 3.0.0
info:
  title: ihe-xds-api
  description: API til integration og test af IHE XDS infrastruktur
  version: "1.0.0"
  contact:
    email: development@kvalitetitsit.dk
tags:
  - name: ihe-xds-api
    description: Ihe Xds Api

servers:
  - url: '{protocol}://{environment}:{port}'
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      environment:
        enum:
          - localhost # Docker-compose setup
        default: localhost # Development
      port:
        enum:
          - 8080
        default: 8080
paths:
  /v1/iti18:
    get:
      tags:
        - IHEXDS
      summary: Call the thugs service
      description: Post your name and get some hugs or meet some thugs.
      requestBody:
        description: Your name
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/iti18Request'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iti18Response'

components:
  responses:
    '400':
      description: "Bad Request. This could be because: * One of the required parameters/properties are missing or is empty <br> * Length of input is exceeding maximum length <br> (See a possible detailed error message in the in the response.)"
    '401':
      description: "Unauthorized. This could be because: <br> * The calling system has not been properly authenticated."
    '403':
      description: "Forbidden. This could be because: <br> * The requested information does not belong the organisation of the user <br> * The calling user does not have the required roles"
  schemas:
    iti18Response:
      type: object
      required:
        - patientId
        - documentId
      properties:
        patientId:
          description: Patientens Id (CPR)
          type: string
          nullable: false
          example: "2512489996"
        documentId:
          description: Dokumentets Id
          type: string
          nullable: false
          example: "987598435735.54587493.454353"

    iti18Request:
      type: object
      required:
        - patientId
      properties:
        patientId:
          description: Patientens Id (CPR)
          type: string
          example: "2512489996"
