openapi: 3.0.0
info:
  title: ihe-xds-api
  description: API til integration og test af IHE XDS infrastruktur
  version: "1.0.0"
  contact:
    email: development@kvalitetitsit.dk
tags:
  - name: ihe-xds-api
    description: Ihe Xds Api

servers:
  - url: '{protocol}://{environment}:{port}'
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      environment:
        enum:
          - localhost # Docker-compose setup
        default: localhost # Development
      port:
        enum:
          - 8080
        default: 8080
paths:
  /v1/iti18:
    post:
      tags:
        - IHEXDS
      summary: search XDS as a healthcare professional
      description: search XDS as a healthcare professional
      requestBody:
        description: Your name
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/iti18Request'
      responses:
        '200':
          description: Ok with list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iti18Response'


  /v1/codes/classCode:
    get:
      tags:
        - Class codes
      summary: Get class code and name of class code
      description: Get class code and name of class code
      responses:
        '200':
          description: Ok with list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/code'

  /v1/codes/availabilityStatusCode:
    get:
      tags:
        - Availability codes
      summary: Get code and name of availability
      description: Get code and name of availability
      responses:
        '200':
          description: Ok with list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/code'

  /v1/codes/formatCode:
    get:
      tags:
        - Format codes
      summary: Get code and name of format codes
      description: Get code and name of format codes
      responses:
        '200':
          description: Ok with list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/code'
  /v1/codes/healthCareFacilityType:
    get:
      tags:
        - Health Care Facility Type Codes
      summary: Get code and name of healthCareFacilityType codes
      description: Get code and name of healthCareFacilityType codes
      responses:
        '200':
          description: Ok with list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/code'

  /v1/codes/practiceSettingCode:
    get:
      tags:
        - Practice setting code
      summary: Get code and name of practiceSettingCode
      description: Get code and name of practiceSettingCode
      responses:
        '200':
          description: Ok with list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/code'

  /v1/codes/objectTypeCode:
    get:
      tags:
        - Object type code
      summary: Get code and name of objectType
      description: Get code and name of objectType
      responses:
        '200':
          description: Ok with list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/code'

  /v1/codes/eventCode:
    get:
      tags:
        - Event code
        - Event code scheme
      summary: Get code and name of event code and scheme
      description: Get code and name of event code and scheme
      responses:
        '200':
          description: Ok with list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/code'

  /v1/codes/typeCode:
    get:
      tags:
        - Type code
      summary: Get code and name of type code and scheme
      description: Get code and name of type code and scheme
      responses:
        '200':
          description: Ok with list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/code'

  /v1/request/{requestId}:
    get:
      tags:
        -  Request result
      summary: Get  Request result SOAP/XML
      description: Get  Request result SOAP/XML
      parameters:
        - in: path
          name: requestId
          schema:
            type: string
          required: true
          description: UUID of the request to get
      responses:
        '200':
          description: Ok with list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/downloadLog'



  /v1/response/{responseId}:
    get:
      tags:
        -  Response result
      summary: Get  Response result SOAP/XML
      description: Get  Response result SOAP/XML
      parameters:
        - in: path
          name: responseId
          schema:
            type: string
          required: true
          description: UUID of the response to get
      responses:
        '200':
          description: Ok with list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/downloadLog'
components:
  responses:
    '400':
      description: "Bad Request. This could be because: * One of the required parameters/properties are missing or is empty <br> * Length of input is exceeding maximum length <br> (See a possible detailed error message in the in the response.)"
    '401':
      description: "Unauthorized. This could be because: <br> * The calling system has not been properly authenticated."
    '403':
      description: "Forbidden. This could be because: <br> * The requested information does not belong the organisation of the user <br> * The calling user does not have the required roles"
  schemas:
    iti18QueryResponse:
      type: object
      required:
        - patientId
        - documentId
      properties:
        patientId:
          description: Patientens Id (CPR)
          type: string
          nullable: false
          example: "2512489996"
        documentId:
          description: Dokumentets Id Or unique ID
          type: string
          nullable: false
          example: "987598435735.54587493.454353"
        repositoryID:
          description: Repostory ID
          type: string
          nullable: false
          example : "1.2.208.192.100.101"
        documentType:
          description: Document type
          type: string
          nullable: false
          example: "Dato og tidspunkt for møde mellem patient og sundhedsperson"
        serviceStart:
          description: The start service from date-time as Long
          type: integer
          format: int64
          example: "1664349302510"
        serviceEnd:
          description: The start service to date-time as Long
          type: integer
          format: int64
          example: "1664349302510"
        document:
          description: The uploaded document
          type: object
          $ref: '#/components/schemas/document'

    iti18Response:
      type: object
      properties:
        queryResponse:
          description: The query responses results
          type: array
          items:
            $ref: '#/components/schemas/iti18QueryResponse'
          example: "[..], [..]"
        requestId:
          description: The request Id as UUID
          type: string
          example: "f638012a-8c49-44b2-b647-9c3595b9e398"
        responseId:
          description: The response Id as UUID
          type: string
          example: "f638012a-8c49-44b2-b647-9c3595b9e398"


    code:
      type: object
      required:
        - name
        - code
      properties:
        name:
          description: The name of the code
          type: string
          example: "Clinical report"
        code:
          description: The code value
          type: string
          example: "001"
        scheme:
          description: the scheme for the code
          type: string
          example: "1.2.208.184.100.10"

    healthcareProfessionalContext:
      type: object
      properties:
        authorizationCode:
          description: The doctor authrization for the person responseible for the request
          type: string
          example: "CX8324"
        consentOverride:
          description: 'Break the glass'
          type: boolean
          example: "false"
        role:
          description: 'Role of the actor'
          type: string
          example: "User, Læge"

    iti18QueryParameter:
      type: object
      required:
        - patientId
        - availabilityStatus
      properties:
        patientId:
          description: Patientens Id (CPR)
          type: string
          example: "2512489996"
        typeCode:
          description: Type Code
          $ref: '#/components/schemas/codeQuery'
        formatCode:
          description: Format Code
          $ref: '#/components/schemas/codeQuery'
        healthcareFacilityTypeCode:
          description: Healthcare facility code
          $ref: '#/components/schemas/codeQuery'
        eventCode:
          description: Event Code
          $ref: '#/components/schemas/codeQuery'
        practiceSettingCode:
          description: Practice setting code
          $ref: '#/components/schemas/codeQuery'
        documentType:
          description: Document type
          type: array
          items:
            type: string
        startFromDate:
          description: The start service from date-time as Long
          type: integer
          format: int64
          example: "1664349302510"
        startToDate:
          description: The start service to date-time as Long
          type: integer
          format: int64
          example: "1664349302510"
        endFromDate:
          description: The end service from date-time as Long
          type: integer
          format: int64
          example: "1664349302510"
        endToDate:
          description: The end service to date-time as Long
          type: integer
          format: int64
          example: "1664349302510"
        availabilityStatus:
          description: The availability result
          type: string



    iti18Request:
      type: object
      required:
        - queryParameters
        - credentialId
        - context
      properties:
        queryParameters:
          description: query parameters related to iti-18 query
          $ref: '#/components/schemas/iti18QueryParameter'
        credentialId:
          description: The credential to use (identified by id)
          type: string
          example: "credentialid"
        context:
          description: the context in which to make the query
          $ref: '#/components/schemas/healthcareProfessionalContext'

    codeQuery:
      type: object
      required:
        - code
        - codeScheme
      properties:
        code:
          description: Code value from the search query
          type: string
          example: "74468-0"
        codeScheme:
          description: Code scheme from the search query
          type: string
          example: "2.16.840.1.113883.6.1"


    document:
      type: object
      properties:
        prop1:
          description: The first property
          type: string
          example: "test"

    downloadLog:
      type: object
      properties:
        payload:
          description: They payload of the request or response
          type: string
          example: "<xml>...<xml>"

