openapi: 3.0.0
info:
  title: ihe-xds-api
  description: API til integration og test af IHE XDS infrastruktur
  version: "1.0.0"
  contact:
    email: development@kvalitetitsit.dk
tags:
  - name: ihe-xds-api
    description: Ihe Xds Api

servers:
  - url: '{protocol}://{environment}:{port}'
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      environment:
        enum:
          - localhost # Docker-compose setup
        default: localhost # Development
      port:
        enum:
          - 8080
        default: 8080
paths:
  /v1/iti18/healthcareProfessional:
    get:
      tags:
        - IHEXDS
      summary: search XDS as a healthcare professional
      description: search XDS as a healthcare professional
      requestBody:
        description: Your name
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/iti18HealthCareProfessionalRequest'
      responses:
        '200':
          description: Ok with list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/iti18Response'


components:
  responses:
    '400':
      description: "Bad Request. This could be because: * One of the required parameters/properties are missing or is empty <br> * Length of input is exceeding maximum length <br> (See a possible detailed error message in the in the response.)"
    '401':
      description: "Unauthorized. This could be because: <br> * The calling system has not been properly authenticated."
    '403':
      description: "Forbidden. This could be because: <br> * The requested information does not belong the organisation of the user <br> * The calling user does not have the required roles"
  schemas:
    iti18Response:
      type: object
      required:
        - patientId
        - documentId
      properties:
        patientId:
          description: Patientens Id (CPR)
          type: string
          nullable: false
          example: "2512489996"
        documentId:
          description: Dokumentets Id
          type: string
          nullable: false
          example: "987598435735.54587493.454353"

    healthcareProfessionalContext:
      type: object
      required:
        - actingUserId
        - authorizationCode
        - consentOverride
      properties:
        actingUserId:
          description: The id of the person making the request
          type: string
          example: "2512489996"
        responsibleUserId:
          description: The id of the person responsible for the request (if different from actingUserId)
          type: string
          example: "2512489996"
        authorizationCode:
          description: The doctor authrization for the person responseible for the request
          type: string
          example: "CX8324"
        consentOverride:
          description: 'Break the glass'
          type: boolean
          example: "false"
        organisationCode:
          description: The code of the organisation where the responsible is located
          type: string
          example: "7879798789"

    iti18QueryParameter:
      type: object
      required:
        - patientId
      properties:
        patientId:
          description: Patientens Id (CPR)
          type: string
          example: "2512489996"

    iti18HealthCareProfessionalRequest:
      type: object
      required:
        - queryParameters
        - credentialId
        - context
      properties:
        queryParameters:
          description: query parameters related to iti-18 query
          $ref: '#/components/schemas/iti18QueryParameter'
        credentialId:
          description: The credential to use (identified by id)
          type: string
          example: "credentialid"
        context:
          description: the context in which to make the query
          $ref: '#/components/schemas/healthcareProfessionalContext'
